### ISSUE TITLE
[Feature Request] Alphabetical sorting for lists

### ISSUE THREAD

**Issue by lilacpixel** [hoarder-app/hoarder#315]
When lists are created in Hoarder, they're always displayed in the order that they were created. Once you have enough lists, it becomes a bit less convenient to scan the sidebar for the right one. Would an alphabetical sort for lists be a useful addition for anyone else?

Thanks for considering it!

(Side note: I tried digging into the code base to see if I could add this feature, but I quickly got overwhelmed by the task. If anyone has suggestions for where I might be able to pick up more useful TypeScript, I'd love to be able to tackle more of these requests myself 😊)

**Comment by kamtschatka** [comment]
I personally believe it makes sense. I was hoping to actually allow ordering them any way you want, but ordering alphabetically makes sense either way. Sorting them however you want is much more complicated, so even as an intermediary step it would make sense in my opinion

**Comment by PurplePrawns** [comment]
Yes! :) I was just thinking that after creating the 15th list today...

**Comment by raviwarrier** [comment]
I still think there's a need for sorting by date. It currently sorts by latest first, but I have 1900+ bookmarks I imported and I have to press "Load more" 1900/20 = 85 times before I get to the first one. (I don't know what is the first bookmark, just in case some one wants to suggest to search for it or go to it via a tag).

It also needs pagination functionality (rather than load more onto one page), but will be creating a feature request for it.

**Comment by MohamedBassem** [comment]
@raviwarrier This issue is about sorting the list names in the sidebar. Having different ordering for bookmarks in the grid makes a lot of sense, please open another issue for it.

**Comment by raviwarrier** [comment]
My mistake MB. Will do. :)
