### ISSUE TITLE
[FR] Support web clipping in the browser extensions

### ISSUE THREAD

**Issue by huyz** [hoarder-app/hoarder#330]
To be able to clip and cache web pages that are behind a paywall or a login, or whose DOM we've already cleaned up by zapping unneeded elements, it would be nice to support web clipping functionality like Evernote's (still best-of-breed, surprisingly) web clipper.

I see the two most important modes as:
- "article" or "full page"
- "simplified article" (a.k.a. "readable" or "uncluttered" view)

Other modes are useful but could be added much later:
- snapshot
- multi-select
- PDF

These use cases overlap with a feature to upload SingleFile html files (FR https://github.com/hoarder-app/hoarder/issues/329) but this feature of course provides convenience.

(Note, this is similar to the [FR on LinkWarden](https://github.com/linkwarden/linkwarden/issues/186))

**Comment by MohamedBassem** [comment]
Hi, this is already planned and tracked in #172. I'll try to prioritize it. If you don't mind, I'll merge this issue with #172

**Comment by dionorgua** [comment]
Note: While web clipping is good thing to have, but please keep in mind that SingeFile have a lot of features to save HTML properly. So redoing it again may be just waste of time.

Also SingleFile can automatically 'upload' HTML files to a few cloud providers:
![image](https://github.com/user-attachments/assets/14d546bd-1d8b-4c7a-8262-4025776b199e)

Maybe it'll be much easier to just implement REST or DAV PUT endpoint that will be similar to current "Hoard" button?
In such case it'll still be different than https://github.com/hoarder-app/hoarder/issues/329 because #329 is mostly about importing existing HTML files on disk.

**Comment by HoroTW** [comment]
Just for future readers, this has been done and a guide to using Hoarder with SingleFile is here: https://docs.hoarder.app/next/Guides/singlefile
