### ISSUE TITLE
[Feature Request] Allow 3rd party crawling

### ISSUE THREAD

**Issue by aaroneden** [hoarder-app/hoarder#339]
Allow connections to Zapier or systems like FireCrawl for more robust crawling

**Comment by kamtschatka** [comment]
from what I can see they only provide markdown, whereas the link scraping in hoarder uses html, so it would be more like a text bookmark and not a link bookmark.

From previous responses to issues like this, the intention is rather to keep hoarder clean instead of adding all kinds of integrations for all kinds of (paid) services.
Can't you utilize the CLI and push the markdown you scraped using those services to hoarder?

**Comment by MohamedBassem** [comment]
Hoarder currently supports browserless (via `BROWSER_WEBSOCKET_URL`), given that it's the container that's used on unraid for chrome, and that it still keeps hoarder 3rd party provider agnostic.

We don't currently plan to support more 3rd party crawling unless there's strong demand from the community.

**Comment by MohamedBassem** [comment]
Closing this as it's unlikely it'll get implemented.
