### ISSUE TITLE
Export/Import bookmarks

### ISSUE THREAD

**Issue by philskents** [hoarder-app/hoarder#522]
I am moving from local auth to OIDC and need to export my bookmarks from the admin account to move them to my OIDC created account (the email addresses on the two accounts are different).

I do not see an option to export my bookmarks, am I missing something?

**Comment by MohamedBassem** [comment]
@philskents I landed this feature recently and it'll be available in the next release. However, It might be more efficient to just change the email of your admin account and enable oauth account linking so that you don't need to recrawl all of your bookmarks. If that's something you're interested in doing, let me know and I can guide you on how to do it.

**Comment by MohamedBassem** [comment]
@philskents Do you want to join us on discord to guide you with that? Would be faster than the comments here.

**Comment by DST73** [comment]
Hi,
I would like to export all my bookmarks to have something like a backup.
Where do I find that mentioned feature to export all bookmarks?

Thank you
