### ISSUE TITLE
Automated List Assignment using LLMs

### ISSUE THREAD

**Issue by gercollo** [hoarder-app/hoarder#664]
### Describe the feature you'd like

Currently, LLMs can add tags to hoarded links. Extending this functionality to automatically categorize links into predefined lists would greatly enhance organization and accessibility.

### Use Case
When saving a link, the LLM would:
1. Analyze the content/URL (existing functionality)
2. Add relevant tags (existing functionality)
3. Automatically assign the link to appropriate list(s) based on custom user prompts (new)

### Example Scenarios
- Recipe links → "Cooking" list
- Programming tutorials → "Dev Resources" list  
- Travel guides → "Travel Planning" list

### Can the goal of this request already be achieved via other means?

Potentially by merging the concept of a tag and list, and putting tags on the main sidebar. However, this would be a drastic change from the current version too.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by kamtschatka** [comment]
I don't think that makes sense tbh. 
We are planning to add a way to make lists that are based on search queries (see https://github.com/hoarder-app/hoarder/issues/65), so instead you'll be able to just create your lists and filter for specific tags. 
There is also a PR open that will allow you to force the AI to assign only tags that you have created, so instead of having the AI assign your bookmarks to a list, you'd have the AI tag your bookmarks with a certain tag and then your lists would e.g. search for all bookmarks with certain tags.

**Comment by gercollo** [comment]
Oh cool, the AI for user-created tags will indeed make it obsolete. Thanks!
