### ISSUE TITLE
cannot link the server with insecure protocol(HTTP) in IOS app

### ISSUE THREAD

**Issue by DeAntiWang** [hoarder-app/hoarder#679]
### Describe the Bug

![IMG_5733](https://github.com/user-attachments/assets/223f8d49-a5d5-439f-9402-0044d028246e)

Non-secure links (http) are disabled by default in ios apps and need to be enabled in info.plist.

### Steps to Reproduce

1. open the hoarder app on ios
2. input a HTTP protocol server link 
3. debug the connection 

### Expected Behaviour

we need connect our server during http 

### Exact Hoarder Version

v0.19.0

**Comment by MohamedBassem** [comment]
Yeah, this is a known issue. That I still don't know how to solve :)

**Comment by robalees** [comment]
Any updates here? I'm getting the same error 

`Running connection test ...

Using address: http://10.0.1.128:3000

Network connection failed: The Internet connection appears to be offline.`

Is the only option to setup HTTPS?

**Comment by brantfaircloth** [comment]
I'm also getting this error on iPad OS and iPhone OS (18.2 on each). Hoarder v0.20.0 installed w/ Docker compose.

**Comment by bufsize** [comment]
Could this help maybe: https://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi?

I get the same error when testing the connection to the Hoarder server running on my Mac through the Hoarder iOS app. I've set up a Tailnet by Tailscale to connect my iPhone and Mac. I can successfully access the server using the Google Chrome app on my iPhone but not through the Hoarder mobile app.

**Comment by MohamedBassem** [comment]
@bufsize We already have this enabled in the app's configuration.

![Uploading Screenshot 2024-12-29 at 11.22.07 AM.png…]()

Honestly, it's not clear to me so far why iOS is still refusing to connect over http with that :(

**Comment by MohamedBassem** [comment]
I think I found the problem:

<img width="708" alt="Screenshot 2024-12-29 at 3 35 39 PM" src="https://github.com/user-attachments/assets/7d5a2331-3167-414a-acc5-ee57055097fc" />

We have local networking enabled, so probably that's why it's getting ignored. I'll try to drop the local networking flag, and see if it helps.

**Comment by bufsize** [comment]
Do you know if the fix worked? If so, when will it be released? Thanks

**Comment by tusharm74** [comment]
Has this been fixed for IOS ? Same server works fine on android device for me, its only IOS where i face the same problem when the server is connected via tailscale, when connecting via local network IOS also works fine.

Thanks

**Comment by MohamedBassem** [comment]
Still haven't uploaded the release to apple unfortunately. Will try to do this this weekend.

**Comment by bufsize** [comment]
> Still haven't uploaded the release to apple unfortunately. Will try to do this this weekend.

Any updates on this? 🙏

**Comment by TaciteOFF** [comment]
Still not working
