### ISSUE TITLE
[Docs] Document importing links from other platforms

### ISSUE THREAD

**Issue by MohamedBassem** [hoarder-app/hoarder#7]

**Comment by alexkutsan** [comment]
I would like to try this beautiful app.
Buty I am aleady using Linkwarden and don't wan't to loos all my bookmarks. 
Would be nice to have importing options of Linkwarden json backup data.

**Comment by MohamedBassem** [comment]
> I would like to try this beautiful app.
> 
> Buty I am aleady using Linkwarden and don't wan't to loos all my bookmarks. 
> 
> Would be nice to have importing options of Linkwarden json backup data. 

Hi 👋 If you have some bash skills, you can definitely use hoarder's CLI mentioned in https://docs.hoarder.app/import to do mass imports. If not, I can craft the commands up and put them there :)

**Comment by lucius346346** [comment]
Works great, but I wish I could add links directly to Archive/list. Manually archiving hundreds of bookmarks would be a pain.

**Comment by MohamedBassem** [comment]
@lucius346346 that should be an extremely easy fix :) I'll add support for that later today :)

**Comment by MohamedBassem** [comment]
@lucius346346 I've added support in the CLI to mass add items to lists (or to archive them). New docs are here: https://docs.hoarder.app/command-line

**Comment by MohamedBassem** [comment]
@kamtschatka added support for uploading chrome bookmarks and updated the docs

**Comment by rkmfl** [comment]
> I would like to try this beautiful app. Buty I am aleady using Linkwarden and don't wan't to loos all my bookmarks. Would be nice to have importing options of Linkwarden json backup data.

@alexkutsan - could you explain the areas where Hoarder-App outshines LinkWarden?

Thank you in advance.

**Comment by alexkutsan** [comment]
@rkmfl mainly vibes :-) 

I haven't tried Hoarder in practice yet because I was a bit lazy to use the CLI with bash to perform a Linkwarden-to-Hoarder export of my existing bookmarks. I only experimented with the demo and did some small-scale exploring using Docker Compose on my localhost.

I like how Hoarder looks and appreciate the automatic tagging feature (which Linkwarden seems to lack). The availability of Android and iOS apps is also a big benefit for me. With Linkwarden, I use an iOS shortcut to create bookmarks from my iPad, but I can't do this from Android at all (there is a PWA app available for Android, but the "share" dialog does not include PWA apps).

**Comment by treyg** [comment]
@alexkutsan @kamtschatka I wrote a couple simple scripts to make importing from linkwarden a little easier while I was going through the process, if that helps: https://github.com/treyg/linkwarden-to-hoarder

I'd be happy to contribute and add steps to the docs for LW import, but it would feel a little clunky to include multiple scripts in the import docs just for one specific app (linkwarden). Let me know if you have any thoughts what the best approach would be and I can open a PR. I could also add feature to allow hoarder to import directly from linkwarden, if you think it would be worthwhile, @MohamedBassem
